# Generated by Django 2.1.1 on 2018-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='body',
        ),
        migrations.AddField(
            model_name='request',
            name='role',
            field=models.CharField(choices=[('1', 'Request new role'), ('author', 'Author'), ('editor', 'Editor'), ('edit_and_author', 'Editor and author'), ('exec', 'Executive editor')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', max_length=300, upload_to=''),
        ),
    ]
